name: Sync Gitee Repos To Github

on:
  push:
    branches:
      - master, dev-binocular
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Get current repository name
      id: info
      uses: actions/github-script@v3.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          return context.repo.repo;

    - name: Sync Github Repos To Gitee 
      uses: Yikun/hub-mirror-action@v1.1
      with:
        src: github/numajinfei 
        dst: gitee/JadeHu 
        #src: gitee/JadeHu
        #dst: github/numajinfei
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} 
        dst_token:  ${{ secrets.GITEE_TOKEN }} 
        account_type: user 
        #使用ssh方式进行clone，也可以使用https
        clone_style: "ssh" 
        debug: true 
        force_update: true 
        #static_list: "binocular-vision" 
        static_list: '${{ steps.info.outputs.result }}'
        timeout: '600s'  
