name: Sync Gitee Repos To Github

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Get repo and time
      id: info
      uses: actions/github-script@v3.1
      with:
        result-encoding: string
        script: |
          core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
          core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
          return context.repo.repo;

    - name: Cache src repos
      uses: actions/cache@v2.1.3
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
        restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-
    
    - name: Sync Github Repos To Gitee 
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/numajinfei 
        dst: gitee/JadeHu 
        #src: gitee/JadeHu
        #dst: github/numajinfei
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} 
        #dst_token:  ${{ secrets.GITEE_TOKEN }} 
        account_type: user 
        #使用ssh方式进行clone，也可以使用https
        clone_style: "ssh" 
        #clone_style: "https"
        debug: true 
        force_update: true 
        #static_list: "binocular_vision" 
        static_list: '${{ steps.info.outputs.result }}'
        timeout: '600s'  
