name: Sync

on: 
  push:
    branches: [ master, main ]
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          #source-repo: "git@github.com:numajinfei/binocular_vision.git"
          source-repo: "https://github.com/numajinfei/binocular_vision.git"
          destination-repo: "git@gitee.com:JadeHu/binocular_vision.git"
          #source-repo: "git@github.com:qianzai/mydocs.git"
          #destination-repo: "git@gitee.com:BuZM/mydocs.git"
          
  #mirror:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: mirror
  #      uses: mathisve/git-mirror-action@latest
  #      with:
  #        originalURL: https://github.com/numajinfei/binocular_vision.git
  #        originalBranch: master
  #        mirrorURL: https://gitee.com/JadeHu/binocular_vision.git
  #        mirrorBranch: master
  #        verbose: true
  #        force: true
  #        tags: true
  #        pat: ${{ secrets.GITEE_TOKEN }}
