name: Sync Gitee Repos To Github

on:
  push:
    branches:
      - master, dev-binocular
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Get current repository name
      id: info
      uses: actions/github-script@v3.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          echo "context.repo.repo";
          return context.repo.repo;

    - name: Sync Github Repos To Gitee 
      uses: Yikun/hub-mirror-action@v1.1
      with:
        #源端账户名
        src: github/numajinfei 
        #目的端账户名
        dst: gitee/JadeHu 
        #src: gitee/JadeHu
        #dst: github/numajinfei
        #SSH密钥对中的私钥，即 id_rsa
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} 
        #Gitee账户的私人令牌
        dst_token:  ${{ secrets.GITEE_TOKEN }} 
        #账户类型
        account_type: user 
        #使用ssh方式进行clone，也可以使用https
        clone_style: "ssh" 
        #启用后会显示所有执行命令
        debug: true 
        #启用后，强制同步，即强制覆盖目的端仓库
        force_update: true 
        #静态同步列表，在此填写需要同步的仓库名称，可填写多个
        #static_list: "binocular-vision" 
        static_list: '${{ steps.info.outputs.result }}'
        #git超时设置，超时后会自动重试git操作
        timeout: '600s'  
