name: Sync Gitee Repos To Github

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Gitee 
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/numajinfei 
        dst: gitee/JadeHu 
        #src: gitee/JadeHu
        #dst: github/numajinfei
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} 
        dst_token:  ${{ secrets.GITEE_TOKEN }} 
        account_type: org
        #使用ssh方式进行clone，也可以使用https
        #clone_style: "ssh" 
        #clone_style: "https"
        #debug: true 
        force_update: true 
        static_list: "binocular_vision"
        #static_list: '${{ steps.info.outputs.result }}'
        #timeout: '600s'  
